import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import PieChart from "../components/chart/PieChart";
import BarChart, { Data } from "../components/chart/BarChart";
import TotalAvgChart from "../components/chart/TotalAvgChart";
import TotalAvgPie from "../components/chart/TotalAvgPie";
import LineChart from "../components/chart/LineChart";
import LineAvgChart from "../components/chart/LineAvgChart";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [chartData, setChartData] = useState<Data[]>();
  const [grafTilVisning, setGrafTilVisning] = useState("");

  useEffect(() => {
    fetch("http://localhost:3001/api/readFile")
      .then((response) => response.json())
      .then((data) => setChartData(data));
  }, []);
  console.log(chartData);

  let fag;
  let unique;
  if (chartData) {
    fag = chartData.map((o) => {
      return o.FAG;
    });
    unique = fag.filter((item, i, ar) => ar.indexOf(item) === i);
  }

  function changeSelect(target: React.ChangeEvent<HTMLSelectElement>) {
    let valgtGraf = target.target.value;
    setGrafTilVisning(valgtGraf);
  }

  if (chartData)
    return (
      <>
        <Head>
          <title>Graph data</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* <link rel="icon" href="/favicon.ico" /> */}
        </Head>
        <main className={styles.main}>
          <h1>Graf visning av Fagprøve data</h1>
          <h3>velg graf type</h3>
          <select
            name="fag"
            id="fag"
            style={{ textAlign: "center" }}
            onInput={changeSelect}
          >
            <option value="bar">Bar</option>
            <option value="pie">Pie</option>
            <option value="line">Line</option>
          </select>

          {grafTilVisning == "pie" && (
            <>
              <PieChart chartData={chartData} />
              <TotalAvgPie chartData={chartData} />
            </>
          )}
          {grafTilVisning == "bar" && (
            <>
              <BarChart chartData={chartData} />{" "}
              <TotalAvgChart chartData={chartData} />
            </>
          )}
          {grafTilVisning == "line" && (
            <>
              <LineChart chartData={chartData} />
              <LineAvgChart chartData={chartData} />
            </>
          )}
        </main>
      </>
    );
}
